### PR TITLE
release: v1.0.0b1

### PR DESCRIPTION
**Pull request by krzysztof**
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

### CODE REVIEW

**Comment by lnielsen** [comment]
Docs are currently not building correctly: http://invenio-mail.readthedocs.io

**Comment by krzysztof** [comment]
@lnielsen Still not building after adding the dependency to "docs"

**Comment by krzysztof** [comment]
@lnielsen docs should build once this is merged: https://github.com/inveniosoftware/invenio-mail/pull/33

**Comment by lnielsen** [comment]
#32 merged. Just waiting to see if read the docs builds correctly.

**Comment by krzysztof** [comment]
@lnielsen docs built correctly

**Pull request merged**
